Repository arduino/go-win32-utils, pull requests merged in 2023-03, with the labels that each got.

#4 Added `devicenotification` implementation
  devicenotification/devicenotification.go
Labels: enhancement

#5 Add CI workflow to check Markdown files for problems
  .github/workflows/check-markdown-task.yml
  .gitignore
  .markdown-link-check.json
  .markdownlint.yml
  .markdownlintignore
  README.md
  Taskfile.yml
  package-lock.json
  package.json
Labels: enhancement

#6 Add CI workflow to synchronize with shared repository labels
  .github/workflows/sync-labels.yml
  README.md
Labels: enhancement

#7 Add CI workflow to validate Taskfiles
  .github/workflows/check-taskfiles.yml
  README.md
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#9 Add CI workflow to test Go code
  .github/workflows/test-go-task.yml
  .gitignore
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#8 Add CI workflow to lint and check formatting of Go code
  .github/workflows/check-go-task.yml
  README.md
  Taskfile.yml
  devicenotification/devicenotification.go
  doc.go
  syscall_windows.go
Labels: type: enhancement, topic: infrastructure

#10 Add CI workflow to check the license file
  .github/workflows/check-license.yml
  LICENSE.txt
  README.md
  devicenotification/devicenotification.go
  doc.go
  examples_test.go
  shell32_fallback.go
  shell32_windows.go
  syscall_windows.go
Labels: type: enhancement, topic: infrastructure

#11 Add license header to project's files
  devicenotification/devicenotification.go
  doc.go
  examples_test.go
  shell32_fallback.go
  shell32_windows.go
  syscall_windows.go
Labels: type: enhancement, topic: documentation
